select * from Price;
select * from Topping;
select * from Discount;
select * from Pizza;
select * from Orders;
select * from Customer;
select * from PizzaTopping;
select * from PizzaDiscount;
select * from OrderDiscount;
